owner: William Granados
url: "wgranados.github.io"
baseurl: ""

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

social:
    email: me@wgma.ca
    github: wgranados 
    linkedin: wlgranados 
    lastfm: wgma00
    yelp: wgma
    tripadvisor: Profile/wgma00
    stackoverflow: 5972611/wgma00
