owner: William Granados
url: "wlgranados.github.io"
baseurl: ""

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

social:
    email: me@wgma.ca
    github: wlgranados 
    twitter: wgma00
    linkedin: wgma00
    lastfm: wgma00
    yelp: wgma
    stackoverflow: 5972611/wgma00
