owner: William Granados
url: "wlgranados.github.io"
baseurl: "/"
social:
    email: me@wgma00.me
    github: wlgranados 
    twitter: wgma00
    linkedin: wgma00
    lastfm: wgma00
    yelp: wgma
    stackoverflow: 5972611/wgma00
